language: java
jdk:
  - openjdk11

git:
  depth: false

addons:
  sonarcloud:
    organization: "kiwiproject"
    token:
      secure: "RFyAVHCGVEQIa/6QKqdbPJlrEFRbyKFIz0IBi/cO9ElQzYEqKj1/QlrLhIOk9Bi4NFgFv+O53q95rrN8pXPa/lgO3X9gj85XqeAi0QdOHUBhiniVCpEMmE5AUxAGLI0WUgIDZNnFRVOVfxMFLvm2Oni450wxsmpBZL6SM6jmeUF3/aPbb/3xcd8gXsJLh3e96Wr3sHy2FakxrbX9ssZbIrzYHTRV1LyG76ACKKT4/8yN0fcQLT+UsoK/FjP4IWZWYpPXLTwg6QcatoFGnwJC6rgroiDk3SMTRX/LV7XlBOK93wplfsppg79m2mtSwcgJnRVM27mfQuIyYks9pJLOKUQRqo2w5FhbeHutR1zhOHA7K2OoEfYTksgEhHdu8mYRdbUREc6pDt7+CNgqr3klXHTV7SP/l68dO5lWtzdZllw3exsyi/R+dP9xu5CbjGkvfD3HMNRTxIgJV+8OtGJauITDbexbfFciCEps5jjq5EerllOF2o2MrV2jjV7akuQercahVFiLFhkOu4/k3Lz3KFkGu6yCR8q6r2mPfn2poCbxMI49SgMGEfvRXEVBKFdMWeFWJVF6flzLYlBTkqKC0LxVLxpTUnTHahHj0J2VPcl7IhIh0olQPRaSX2bBDZRnrttYv7m5VCUK0jUjD6945NQ3l64lAZFASx65+s33Iz8="

script:
  - mvn -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent
    package org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.projectKey=kiwiproject_dropwizard-client-poller
